sudo: required
services:
  - docker

dist: trusty

env:
  - SHA=$(git rev-parse HEAD)

before_install:
  - docker image build --tag juliocesarmidia/edent-app:$SHA -f ./Dockerfile .

script:
  - docker container run -it --rm --name edent-app --entrypoint "" juliocesarmidia/edent-app:$SHA bash -c "uptime"

after_success:
  - docker image build --tag juliocesarmidia/edent-app:$SHA --tag juliocesarmidia/edent-app:v1.0.0 -f Dockerfile .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker image push juliocesarmidia/edent-app:v1.0.0
  - docker image push juliocesarmidia/edent-app:$SHA

  # docker container run -it --rm -p 80:80 --name edent-app juliocesarmidia/edent-app:v1.0.0
