FROM httpd:2.4.41
LABEL maintainer="julio@blackdevs.com.br"

WORKDIR /usr/local/apache2/htdocs/
COPY . /usr/local/apache2/htdocs/

RUN rm /usr/local/apache2/htdocs/index.html

RUN mv /usr/local/apache2/htdocs/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

RUN apt-get update -y

RUN apt-get install -y -qq php7.3 libapache2-mod-php7.3 \
    php7.3-dev php7.3-mbstring php7.3-mysql php7.3-zip \
    php7.3-curl php7.3-json php7.3-memcached php7.3-pdo

RUN for file in $(ls /etc/php/7.3/mods-available/); do phpenmod "$(echo $file |cut -d'.' -f1)"; done

RUN a2enmod php7.3 && a2enmod rewrite && a2dismod mpm_event && a2enmod mpm_prefork

RUN chmod +x ./docker-entrypoint-httpd.sh
COPY ./docker-entrypoint-httpd.sh /usr/local/apache2/htdocs/docker-entrypoint-httpd.sh

EXPOSE 80
ENTRYPOINT [ "/bin/bash", "/usr/local/apache2/htdocs/docker-entrypoint-httpd.sh" ]
# CMD ["httpd-foreground"]

# Build this image
# docker image build -f Dockerfile -t app .

# Run this image
# docker container run --rm --name app -p 80:80 app
# docker container run --rm -it --name app --entrypoint "" -p 80:80 app bash
