version: '3.4'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: on-failure
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dbodontologia}
      MYSQL_USER: ${MYSQL_USER:-edentuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-edentpass}
    networks:
      - netlocal
    healthcheck:
      test: ["CMD", "curl", "-I", "http://app:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/var/www/html/:rw

  db:
    container_name: db
    image: mysql:8.0
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    expose:
      - 3306
    ports:
      - 3386:3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dbodontologia}
      MYSQL_USER: ${MYSQL_USER:-edentuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-edentpass}
    volumes:
      - mysql-db:/var/lib/mysql
      - ./migrations/data.sql:/docker-entrypoint-initdb.d/data.sql:rw
    networks:
      - netlocal
    restart: on-failure

volumes:
  mysql-db:

networks:
  netlocal:
    driver: bridge
