apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  selector:
    component: app
  ports:
    - port: 80
      targetPort: app-port
      protocol: TCP

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-service
# spec:
#   ports:
#   - port: 80
#     targetPort: todoapp-port
#     protocol: TCP
#   selector:
#     component: todoapp
#   type: LoadBalancer
