apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default

spec:
  # replicas: 3
  revisionHistoryLimit: 100

  selector:
    matchLabels:
      app: edentclient

  strategy:
    type: Recreate

  template:
    metadata:
      name: edent-app
      labels:
        app: edentclient

    spec:
      containers:
        - name: client
          image: juliocesarmidia/edent-app:v1.0.0

          ports:
            - containerPort: 80
              name: client-port

          env:
            - name: MYSQL_HOST
              value: mysql-service

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MYSQL_PASSWORD

            - name: MACHINE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 30

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"

            limits:
              memory: "256Mi"
              cpu: "500m"

      restartPolicy: Always
