apiVersion: v1
kind: Service
metadata:
  name: appclient-service
  namespace: default

spec:
  type: ClusterIP

  selector:
    app: edentclient

  ports:
    - port: 80
      targetPort: client-port
      protocol: TCP
