apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
  labels:
    app: edent

data:
  config.yaml: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    pid-file=/var/run/mysqld/mysqld.pid
    socket=/var/run/mysqld/mysqld.sock
    datadir=/var/lib/mysql
    log-error=/var/log/mysql/error.log
    bind-address=0.0.0.0
    port=3306
    symbolic-links=0
    max_connections=10000
---

# /etc/mysql/mysql.conf.d/mysqld.cnf
