apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  labels:
    app: edent

  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: edent.local
  #   external-dns.alpha.kubernetes.io/ttl: "30"
  #   kubernetes.io/ingress.class: nginx

spec:
  rules:
    # - host: edent.local
    - http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 80
