apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: edent

  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    # - host: edent.ondo.blackdevs.com.br
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-service
              servicePort: 80
