apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: edent
  labels:
    app: edentmysql

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
