apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  namespace: default
  labels:
    app: edent

type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4K # admin
  MYSQL_USER: cm9vdAo= # root
  MYSQL_PASSWORD: YWRtaW4K # admin

# kubectl get secret env-secrets
# kubectl describe secret env-secrets
